#!/usr/bin/env node
/**
 * Generates the site configuration from .env, because a Chrome extension cannot
 * read .env at runtime and manifest "matches" must be static at load time.
 *
 * Writes:
 *   extension/sites.generated.js   - host patterns + view-path regex for the scripts
 *   extension/manifest.json        - patches host_permissions and content_scripts matches
 *
 * Usage:  node build.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const ENV_FILE = path.join(ROOT, '.env');
const SAMPLE_FILE = path.join(ROOT, '.env.sample');
const EXT = path.join(ROOT, 'extension');

/** Minimal .env parser — no dependencies. */
function parseEnv(text) {
  const env = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

function fail(msg) {
  console.error(`build.js: ${msg}`);
  process.exit(1);
}

// .env wins; a fresh checkout with only .env.sample still builds.
const source = fs.existsSync(ENV_FILE) ? ENV_FILE : SAMPLE_FILE;
if (!fs.existsSync(source)) fail('neither .env nor .env.sample found');
if (source === SAMPLE_FILE) {
  console.warn('build.js: no .env found, falling back to .env.sample');
}
const env = parseEnv(fs.readFileSync(source, 'utf8'));

// Chrome match patterns have no place for a port, so "localhost:3000" is accepted and the
// port dropped — the pattern then covers every port on that host, which is what we want.
const dropped = [];
const hosts = (env.SCRAPE_HOSTS || '')
  .split(',')
  .map((h) => h.trim().replace(/^\*?\.?/, '').replace(/\/.*$/, ''))
  .map((h) => {
    const bare = h.replace(/:\d+$/, '');
    if (bare !== h) dropped.push(h);
    return bare;
  })
  .filter(Boolean);
if (!hosts.length) fail('SCRAPE_HOSTS is empty');

const scheme = (env.SCRAPE_SCHEMES || '*').trim();
const viewPattern = env.VIEW_PATH_PATTERN || '\\/view\\/?$|\\/view\\/\\d+\\/?$';

try {
  new RegExp(viewPattern);
} catch (e) {
  fail(`VIEW_PATH_PATTERN is not a valid regex: ${e.message}`);
}

for (const h of hosts) {
  if (!/^[a-z0-9.-]+$/i.test(h)) fail(`"${h}" does not look like a hostname`);
}
if (dropped.length) {
  console.warn(
    `build.js: dropped the port from ${dropped.join(', ')} — ` +
      'match patterns cover every port on the host'
  );
}

// "*.example.com" also matches the bare "example.com" in Chrome match patterns.
const matches = hosts.map((h) => `${scheme}://*.${h}/*`);

/* -------------------------------------------------------------- datastore */
// Where the extension mirrors an exam when "Download as PDF" is clicked. Empty is
// fine — the upload is then skipped and the PDF still downloads.
const datastoreUrl = (env.DATASTORE_API_URL || '').trim().replace(/\/+$/, '');
const datastoreKey = (env.DATASTORE_API_KEY || '').trim();
let datastoreMatch = '';
if (datastoreUrl) {
  let parsed;
  try {
    parsed = new URL(datastoreUrl);
  } catch (e) {
    fail(`DATASTORE_API_URL is not a valid URL: ${e.message}`);
  }
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    fail(`DATASTORE_API_URL must be http or https, got "${parsed.protocol}"`);
  }
  // The service worker's fetch needs a host permission for this origin. Ports are
  // ignored by match patterns, so :8000 needs nothing extra here.
  datastoreMatch = `${parsed.protocol}//${parsed.hostname}/*`;
}

/* ------------------------------------------------- extension/sites.generated.js */
// var (not const/let) so the popup's injected copy of scraper.js degrades gracefully
// when this file is not present in that context.
const generated = `// GENERATED by build.js from .env — do not edit by hand.
// Hosts: ${hosts.join(', ')}
var SCRAPE_HOST_PATTERNS = [
${hosts.map((h) => `  /(^|\\.)${h.replace(/\./g, '\\.')}$/i,`).join('\n')}
];
var VIEW_PATH_PATTERN = ${new RegExp(viewPattern)};
`;
fs.writeFileSync(path.join(EXT, 'sites.generated.js'), generated);

/* --------------------------------------------- extension/datastore.generated.js */
// Separate from sites.generated.js because this one carries the shared secret and
// is gitignored. Always written, so background.js can importScripts() it safely.
const datastore = `// GENERATED by build.js from .env — do not edit by hand.
// Carries the ingest secret, so this file is gitignored. Run: node build.js
var DATASTORE_API_URL = ${JSON.stringify(datastoreUrl)};
var DATASTORE_API_KEY = ${JSON.stringify(datastoreKey)};
`;
fs.writeFileSync(path.join(EXT, 'datastore.generated.js'), datastore);

/* ---------------------------------------------------- extension/manifest.json */
const manifestPath = path.join(EXT, 'manifest.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
// The datastore origin is a host_permission only — nothing is scraped there.
manifest.host_permissions = datastoreMatch ? [...matches, datastoreMatch] : matches;
manifest.content_scripts[0].matches = matches;
fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');

console.log('build.js: wrote the generated files and patched extension/manifest.json');
console.log(`  hosts   : ${hosts.join(', ')}`);
console.log(`  matches : ${manifest.host_permissions.join(' ')}`);
console.log(`  pages   : ${new RegExp(viewPattern)}`);
// The key itself is never printed.
console.log(
  `  store   : ${datastoreUrl || '(unset — upload disabled)'}` +
    (datastoreUrl && !datastoreKey ? '  [no DATASTORE_API_KEY — expect 401]' : '')
);
console.log('Reload the extension at chrome://extensions to pick up the change.');
